### ISSUE TITLE
Full Screen Support 

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [KhubaibKhan4/MediaPlayer-KMP#9] opened 2024-07-10 15:25 UTC
Hi, great work on the library. Would it be possible to allow full-screen support to the Youtube Videos?

**Comment by KhubaibKhan4** [comment] 2024-07-10 17:05
Yes, we can display videos in a full screen but it's working in Web right now. In the upcoming update, I'll definitely add the full screen support for all the platforms. Thank you for your suggestion.

**Comment by LaatonWalaBhoot** [comment] 2024-07-10 17:10
I have a few other questions. Sorry to bother you but is it possible to display youtube videos in a LazyColumn?
And does it preserve the video state while scrolling?
I could not find a sample. Should I open a separate issue for this? @KhubaibKhan4

**Comment by KhubaibKhan4** [comment] 2024-07-11 04:53
Thank you for another suggestion. Yeah, we can display youtube videos inside the lazy column as well but there's no official support for playing youtube videos. We're using JavaFx e.g, So we're it didn't persist the  video state.

**Comment by LaatonWalaBhoot** [comment] 2024-07-11 06:24
Is it possible to persist Video state like Twitter does?
With an Android webview the issue that I face is it causes reload on scrolling
Plus the webview is itself unscrollable and hogs all touches of the lazy column

**Comment by KhubaibKhan4** [comment] 2024-07-11 06:27
There's only way to hold the state using mutableMapState. by that we can hold the current Video Ids and return when we revisit them. This method is mostly used in applications to persist the data.

**Comment by LaatonWalaBhoot** [comment] 2024-07-12 19:08
That would be great. Any idea about the timeline for this @KhubaibKhan4 ?

**Comment by KhubaibKhan4** [comment] 2024-07-13 01:19
I'm planning to work on a sprint of 15 days. Hopefully, will achieve in this sprint.

**Comment by LaatonWalaBhoot** [comment] 2024-07-25 20:10
Any update on this @KhubaibKhan4 ?

**Comment by KhubaibKhan4** [comment] 2024-07-27 06:49
Unfortunately, I'm busy with tickets. Will be doing soon.

**Comment by LaatonWalaBhoot** [comment] 2024-07-27 16:25
No worries. Looking forward to it.

**Comment by LaatonWalaBhoot** [comment] 2024-08-10 18:56
@KhubaibKhan4 saw that you marked it as completed but I couldn't find the functionality

**Comment by KhubaibKhan4** [comment] 2024-08-11 06:47
I accidentally closed this issue. Let me add the functionality of full screen as well.

**Comment by KhubaibKhan4** [comment] 2024-09-22 16:14
@Vaibhav2002  Thank you for your comment. Let me checkout these issues. I'll fix it asap.

**Comment by KhubaibKhan4** [comment] 2024-09-22 17:16
@LaatonWalaBhoot @Vaibhav2002 Thank you for creating the issue. I just added this on the latest version and just updating the version on the Maven Central.

**Closed by KhubaibKhan4** 2024-09-22 17:16 UTC
Labels: enhancement

**Comment by Vaibhav2002** [comment] 2024-09-23 06:27
Hey @KhubaibKhan4 
I tried the latest release 1.1.2, and the fullscreen player still does not work.

https://github.com/user-attachments/assets/14c85fdc-d341-4e39-b5a6-68fa56551b7a

**Comment by KhubaibKhan4** [comment] 2024-09-23 13:48
Let me check it out again.

**Comment by LaatonWalaBhoot** [comment] 2024-09-24 04:50
@KhubaibKhan4 Any update on this?

**Comment by KhubaibKhan4** [comment] 2024-09-24 08:59
Tonight, I'll release a new version. Sore for the delay

**Comment by LaatonWalaBhoot** [comment] 2024-09-24 15:42
That's great. Thanks. Waiting for it eagerly

**Comment by KhubaibKhan4** [comment] 2024-09-24 17:02
Checkout the latest version, Now the full screen is working fine.

**Comment by Vaibhav2002** [comment] 2024-09-25 10:31
@KhubaibKhan4 I tried 1.1.4, and it still does not work

**Comment by KhubaibKhan4** [comment] 2024-09-25 16:34
@Vaibhav2002  Please check again. It's working fine. Please verify it on your emulator or a Personal Device. Thank you

**Comment by KhubaibKhan4** [comment] 2024-09-26 13:40
@Vaibhav2002 Thank you for providing the evidence, I'll check it out and will update here asap. Thank you for being valuable by providing feedback.

**Comment by Vaibhav2002** [comment] 2024-09-29 13:22
@KhubaibKhan4 i tried 1.1.5 , it still does not work, the same thing happens as shown in the recording i sent before
The button does nothing

**Comment by KhubaibKhan4** [comment] 2024-10-01 17:46
Checkout the latest version. Full Screen Is working. Checkout the linkedin post: https://www.linkedin.com/posts/khubaibkhandev_kmp-cmp-kotlin-activity-7246938312261746689-HrL3?utm_source=share&utm_medium=member_desktop

Please share your feedback and recommendations as well.

**Comment by Vaibhav2002** [comment] 2024-10-03 07:22
@KhubaibKhan4 it is working on my personal device but it seems to be a bit buggy
The screen rotates but the video player is not fullscreen, also it feels quite janky even in release build

https://github.com/user-attachments/assets/1861f40b-db07-46e1-b7c3-f95fee99207b

**Comment by KhubaibKhan4** [comment] 2024-10-03 09:03
Please try it on some other devices and let me know, So I can check out the issue because it's working fine on my Personal Device as well as on the emulators.

**Comment by LaatonWalaBhoot** [comment] 2024-10-03 10:16
@KhubaibKhan4 I'm having the same issue in my Samsung device

**Comment by Vaibhav2002** [comment] 2024-10-03 16:31
@KhubaibKhan4 i tried on multiple physical devices, its the same everywhere.

**Comment by KhubaibKhan4** [comment] 2024-10-03 17:15
@LaatonWalaBhoot @Vaibhav2002 I'll checkout and will let you know.

**Comment by Vaibhav2002** [comment] 2024-10-07 05:07
@KhubaibKhan4 any update on this?

**Comment by KhubaibKhan4** [comment] 2024-10-08 18:05
@Vaibhav2002 It's still working fine on my Emulator and my personal device. Please provide me the issue that you are facing. Make sure to checkout the videos on the Network Connection as well as Wifi Connection.

**Comment by LaatonWalaBhoot** [comment] 2024-10-09 17:15
@KhubaibKhan4 I am having the issue on all networks in my Samsung device

**Comment by Vaibhav2002** [comment] 2024-10-11 07:56
@KhubaibKhan4 I tried the latest update on both emulator, physical device as well as wifi and mobile network
It still behaves the same as the last recording I sent, but this release has another bug where video in fullscreen goes completely white and the back button stops working


https://github.com/user-attachments/assets/92af2b50-916b-49cd-95d1-a503e2cf3e50

**Comment by KhubaibKhan4** [comment] 2024-10-11 14:51
Thank you for your video. I'm looking in to it and provide an update asap. Thank you 🙏

**Comment by Vaibhav2002** [comment] 2024-10-15 08:11
@KhubaibKhan4 I tried the new release and the issue is still there
Still my screen rotates, but video player is not fullscreen
and clicking fullscreen button makes screen go white

Exactly same as the recording i sent
